### ISSUE TITLE
Error:  Root element is missing.

### ISSUE THREAD

**Issue by nstrelow** [jellyfin/jellyfin-plugin-anidb#1]
I somehow get this error with the plugin from your unstable repo.

Seems something is wrong.

```
[2021-01-28 22:08:31.052 +01:00] [ERR] Error in "AniDB"
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(Boolean needMoreChars)
   at System.Xml.AsyncHelper.CallBoolTaskFuncWhenFinishCoreAsync[TArg](Task task, Func`2 func, TArg arg)
   at System.Xml.XmlReader.MoveToContentAsync()
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.FetchSeriesInfo(MetadataResult`1 result, String seriesDataPath, String preferredMetadataLangauge)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
```

Also, what is the best Anime scraper?

**Comment by trolhamonas** [comment]
I'm also getting this when doing a library scan. and when trying to search for anime with a ID
`
[2021-03-11 17:35:32.328 +01:00] [ERR] [63] MediaBrowser.Providers.Manager.ProviderManager: Provider "AniDB" failed to retrieve search results
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(Boolean needMoreChars)
   at System.Xml.AsyncHelper.CallBoolTaskFuncWhenFinishCoreAsync[TArg](Task task, Func`2 func, TArg arg)
   at System.Xml.XmlReader.MoveToContentAsync()
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.FetchSeriesInfo(MetadataResult`1 result, String seriesDataPath, String preferredMetadataLangauge)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken
)`

**Comment by fighuass** [comment]
Getting the issue as well (installed from within Jellyfin).

``[2021-03-12 15:42:43.363 +01:00] [ERR] Provider "AniDB" failed to retrieve search results
System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(Boolean needMoreChars)
   at System.Xml.AsyncHelper.CallBoolTaskFuncWhenFinishCoreAsync[TArg](Task task, Func`2 func, TArg arg)
   at System.Xml.XmlReader.MoveToContentAsync()
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.FetchSeriesInfo(MetadataResult`1 result, String seriesDataPath, String preferredMetadataLangauge)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
   at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)

**Comment by oddstr13** [comment]
I was unable to reproduce this exact error, but I found the following which would be responsible for the XML cache file being empty in the first place;
```serilog
Mar 12 21:59:51 1070L jellyfin[1780]: [21:59:51] [ERR] MediaBrowser.Providers.Manager.ProviderManager: Provider AniDB failed to retrieve search results
Mar 12 21:59:51 1070L jellyfin[1780]: System.IO.InvalidDataException: The archive entry was compressed using an unsupported compression method.
Mar 12 21:59:51 1070L jellyfin[1780]:    at System.IO.Compression.Inflater.Inflate(FlushCode flushCode)
Mar 12 21:59:51 1070L jellyfin[1780]:    at System.IO.Compression.Inflater.ReadInflateOutput(Byte* bufPtr, Int32 length, FlushCode flushCode, Int32& bytesRead)
Mar 12 21:59:51 1070L jellyfin[1780]:    at System.IO.Compression.Inflater.ReadOutput(Byte* bufPtr, Int32 length, Int32& bytesRead)
Mar 12 21:59:51 1070L jellyfin[1780]:    at System.IO.Compression.Inflater.InflateVerified(Byte* bufPtr, Int32 length)
Mar 12 21:59:51 1070L jellyfin[1780]:    at System.IO.Compression.DeflateStream.FinishReadAsyncMemory(ValueTask`1 readTask, Memory`1 buffer, CancellationToken cancellationToken)
Mar 12 21:59:51 1070L jellyfin[1780]:    at System.IO.StreamReader.ReadBufferAsync(CancellationToken cancellationToken)
Mar 12 21:59:51 1070L jellyfin[1780]:    at System.IO.StreamReader.ReadToEndAsyncInternal()
Mar 12 21:59:51 1070L jellyfin[1780]:    at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.DownloadSeriesData(String aid, String seriesDataPath, String cachePath, CancellationToken cancellationToken)
Mar 12 21:59:51 1070L jellyfin[1780]:    at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetSeriesData(IApplicationPaths appPaths, String seriesId, CancellationToken cancellationToken)
Mar 12 21:59:51 1070L jellyfin[1780]:    at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
Mar 12 21:59:51 1070L jellyfin[1780]:    at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetSearchResults(SeriesInfo searchInfo, CancellationToken cancellationToken)
Mar 12 21:59:51 1070L jellyfin[1780]:    at MediaBrowser.Providers.Manager.ProviderManager.GetSearchResults[TLookupType](IRemoteSearchProvider`1 provider, TLookupType searchInfo, CancellationToken cancellationToken)
Mar 12 21:59:51 1070L jellyfin[1780]:    at MediaBrowser.Providers.Manager.ProviderManager.GetRemoteSearchResults[TItemType,TLookupType](RemoteSearchQuery`1 searchInfo, BaseItem referenceItem, CancellationToken cancellationToken)
```
