### ISSUE TITLE
Increased Missing root element errors since 10.9.4

### ISSUE THREAD

**Issue by Byorun** [jellyfin/jellyfin-plugin-anidb#70]
Since the Upgrade from 10.9.2 to 10.9.4 I noticed that my NAS was rather noisy Düring library Scans. It was rescanning a lot of series for unknown reasons. This resulted in an instant ban from anidb. 
As soon as you see the message 500 banned in the logs the plugin begins to write empty series.xml files to the cache directory which then result in the missing root element error for consecutive scans. 
Maybe I am imagine things, but I seams to me that this error increases with each scan since more and more series will be rescanned because of the missing/broken cache files

**Comment by nalsai** [comment]
This contains multiple issues:
1. The internal rate limiter needs to be improved.
	It assumes that it runs in sequence, which isn't true anymore (and never was completely true).
	If requests get made without enough time in between, you get banned immediately. Also, once a ban is detected, no new requests should be made until the ban is over.
2. Empty series.xml files get written to the cache directory.
	This shouldn't happen and/or be handled better.

Cache files should be refreshed every 7 days (unless it is configured differently in the plugin settings), regardless of if they are correct or broken.

Also, would you mind telling me how big your library is (how many series and how many episodes in total)? As you may know, scanning too many files in a short period of time always gets you banned, so how to ideally handle very large libraries is still an open question.

I don't know why it was rescanning a lot of series, but the anidb plugin shouldn't have anything to do with that.

**Comment by Byorun** [comment]
My library is about 1500 series with about 15000 episodes. As long as only the new episodes are scanned (between 1-7 depending on how good the current season is) everything is more or less fine. But after the upgrade jellyfin for whatever reason decided to (re)scan more than nessesary which bubbled up more than 100 updates per scan which gets me banned almost instantly

**Comment by nille02** [comment]
could it happen if you get banned and he stores just a empty series.xml ? fir example i got the banned msg while fetching boruto natuto next generations (12661) and the series.xml is empty. if i now want it to search for the missing data he just looks in the xml file and the error pops up. 

```
Aug 30 21:59:32 ubuntuserver jellyfin[1584]: [21:59:32] [INF] Starting /usr/lib/jellyfin-ffmpeg/ffprobe with args -analyzeduration 200M -probesize 1G -i file:"/mnt/anime/Boruto Naruto Next Generations/[TnF]Boruto - Naruto Next Generations 1x42[720p][5608E92E].mp4" -threads 0 -v warning -print_format json -show_streams -show_chapters -show_format
Aug 30 21:59:32 ubuntuserver jellyfin[1584]: [21:59:32] [ERR] Error in AniDB
Aug 30 21:59:32 ubuntuserver jellyfin[1584]: System.Xml.XmlException: Root element is missing.
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(Boolean needMoreChars)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.AsyncHelper.CallBoolTaskFuncWhenFinishCoreAsync[TArg](Task task, Func`2 func, TArg arg)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.XmlReader.MoveToContentAsync()
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.FetchSeriesInfo(MetadataResult`1 result, String seriesDataPath, String preferredMetadataLangauge)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetMetadataForId(String animeId, SeriesInfo info, CancellationToken cancellationToken)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbSeriesProvider.GetMetadata(SeriesInfo info, CancellationToken cancellationToken)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at MediaBrowser.Providers.Manager.MetadataService`2.ExecuteRemoteProviders(MetadataResult`1 temp, String logName, Boolean replaceData, TIdType id, IEnumerable`1 providers, CancellationToken cancellationToken)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]: [21:59:32] [ERR] AniDbImageProvider failed in GetImageInfos for type Series at /mnt/anime/Boruto Naruto Next Generations
Aug 30 21:59:32 ubuntuserver jellyfin[1584]: System.Xml.XmlException: Root element is missing.
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.XmlTextReaderImpl.ParseDocumentContentAsync_ReadData(Boolean needMoreChars)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.AsyncHelper.CallBoolTaskFuncWhenFinishCoreAsync[TArg](Task task, Func`2 func, TArg arg)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at System.Xml.XmlReader.MoveToContentAsync()
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbImageProvider.FindImageUrl(String seriesDataPath)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at Jellyfin.Plugin.AniDB.Providers.AniDB.Metadata.AniDbImageProvider.GetImages(String aniDbId, CancellationToken cancellationToken)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]:    at MediaBrowser.Providers.Manager.ProviderManager.GetImages(BaseItem item, IRemoteImageProvider provider, String preferredLanguage, Boolean includeAllLanguages, CancellationToken cancellationToken, Nullable`1 type)
Aug 30 21:59:32 ubuntuserver jellyfin[1584]: [21:59:32] [INF] Removing virtual season null in series Boruto: Naruto Next Generations
Aug 30 21:59:32 ubuntuserver jellyfin[1584]: [21:59:32] [INF] Removing item, Type: Season, Name: Staffel unbekannt, Path: , Id: 03ee8395-8edd-1858-96f2-d5b7396383a1
Aug 30 21:59:32 ubuntuserver jellyfin[1584]: [21:59:32] [INF] Creating Season Staffel 1 entry for Boruto: Naruto Next Generations
```

Jellyfin v10.9.10
anidb plugin: 9.0.0.0

**Comment by nille02** [comment]
i have the same issue and i just deleted all 0 byte serien.xml files. 
`
find /var/cache/jellyfin/anidb/series -size 0` and you ran remove them with 
`find /var/cache/jellyfin/anidb/series -size 0 -delete`

**Comment by twstagg** [comment]
> find /var/cache/jellyfin/anidb/series -size 0

Thanks. I just setup my "mediastack" with the latest versions of everything this weekend. I'm also having this issue, and I was able to resolve with your guidance!

**Comment by twstagg** [comment]
> > find /var/cache/jellyfin/anidb/series -size 0
> 
> Thanks. I just setup my "mediastack" with the latest versions of everything this weekend. I'm also having this issue, and I was able to resolve with your guidance!

I lied. It _seemed_ to fix the issue at least temporarily by my perception, however,  I honestly don't think I can confirm that as I don't fully understand the issue outside of the troubleshooting I've done with the guidance above. The issue reoccurs after some time, or just never went away. I'm disabling the plugin for now, let me know if I can help debug!

**Comment by crobibero** [comment]
Fixed in https://github.com/jellyfin/jellyfin-plugin-anidb/pull/106
